########################################################################

# avec sudo ansible-playbook -c local config.vm1.yml
---
- hosts: localhost
  tasks:
    # adresse IPv4 avec nmcli (CLI pour NetworkManager)
    # éventuellement, pour supprimer les connexions en trop, faire

    - shell: nmcli connection del "Connexion filaire 1"
      ignore_errors: True

    - shell: nmcli connection del ansible-eth1
      ignore_errors: True


    - shell: nmcli connection add ifname eth1 con-name ansible-eth1 type ethernet ip4 172.16.2.163/28 gw4 172.16.2.162

    - shell: ip route del default
      ignore_errors: True

    
